# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
