# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_choice_text_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes_text',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
