# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_choice_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='id',
        ),
        migrations.AlterField(
            model_name='choice',
            name='email',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
