# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='email',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
