# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_choice_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='email',
        ),
    ]
